# Generated by Django 5.2.4 on 2025-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(max_length=100)),
                ('victim_age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('incident_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('is_electronic', models.BooleanField(default=False)),
                ('electronic_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('perpetrator_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
